-define(LISTENER, jsonevents_server_tcp).
-define(SUPERVISOR, jsonevents_sup).
-define(EVENT_BUS, jsonevents_bus).
-define(SOCKET_CLIENT_SUP, jsonevents_socket_client_sup).
-define(SOCKET_CLIENT_SESSION, jsonevents_socket_client_session).
